version: "3.8"
services:
  api:
    image: vohail/api-user:1.0
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
    depends_on:
      - keycloak
    networks:
      - net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=./realm-export.json
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - net

  frontend:
    image: vohail/frontend-user:1.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=PROD


networks:
  net:
    driver: bridge