spring:
  application:
    name: usermanagement

  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  realm: user
  auth-server-url: http://localhost:8080
  client-id: user_manager
  grant-type: password

server:
  port: 8081